stages:
    - build
    - target_test
    - docs

variables:
    IDF_PATH: "$CI_PROJECT_DIR/esp-idf"
    GIT_STRATEGY: fetch
    GIT_SUBMODULE_STRATEGY: none
    ESP_ZIGBEE_SDK_PATH: "$CI_PROJECT_DIR"
    ESP_ZBOSS_LIB_PATH: "$CI_PROJECT_DIR/esp-zboss-lib"
    ESP_ZBOSS_REPO_URL: "$ESP_ZBOSS_LIB_REPO_URL"
    # tell build system do not check submodule update as we download archive instead of clone
    IDF_SKIP_CHECK_SUBMODULES: 1

before_script:
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo -n "${GITLAB_KEY}" >~/.ssh/id_rsa_base64
  - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 >~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host gitlab.espressif.cn\n\tStrictHostKeyChecking no\n" >>~/.ssh/config

.setup_idf: &setup_idf
  - cd $CI_PROJECT_DIR
  - git clone --depth=1 -b $CI_COMMIT_REF_NAME ${IDF_GIT_REPO_URL} || git clone --depth=1 -b v5.1.3 ${IDF_GIT_REPO_URL}
  - cd esp-idf
  - ./install.sh
  - . ./export.sh
  - export PYTHONPATH="$IDF_PATH/tools/ci/python_packages:$PYTHONPATH"
  - python tools/ci/ci_fetch_submodule.py -s all

.setup_esp_zboss_lib: &setup_esp_zboss_lib
  - cd $CI_PROJECT_DIR
  - git clone --depth=1 -b $CI_COMMIT_REF_NAME ${ESP_ZBOSS_REPO_URL} || git clone --depth=1 -b master ${ESP_ZBOSS_REPO_URL}
  - cd ${ESP_ZBOSS_LIB_PATH}
  - echo $(git branch --show-current)
  - echo $(git log -1 --oneline)
  - cp -r ${ESP_ZBOSS_LIB_PATH} ${IDF_PATH}/components/espressif__esp-zboss-lib

.update_zigbee_lib_script: &update_zigbee_lib_script
  - *setup_idf
  - *setup_esp_zboss_lib
  - cp -r ${ESP_ZIGBEE_SDK_PATH}/components/esp-zigbee-lib ${IDF_PATH}/components/esp-zigbee-lib
  - cd ${ESP_ZIGBEE_SDK_PATH}
  - echo $(git branch --show-current)
  - echo $(git log -1 --oneline)
  - pip install -r tools/ci/requirements-build.txt

.build_rcp_gateway: &build_rcp_gateway
  - mv $CI_PROJECT_DIR/examples/esp_zigbee_gateway/sdkconfig.defaults $CI_PROJECT_DIR/examples/esp_zigbee_gateway/sdkconfig.defaults.ori
  - cp $CI_PROJECT_DIR/tools/ci/sdkconfig_for_gateway_ci.defaults $CI_PROJECT_DIR/examples/esp_zigbee_gateway/sdkconfig.defaults
  - cd $IDF_PATH/examples/openthread/ot_rcp
  - echo "CONFIG_OPENTHREAD_NCP_VENDOR_HOOK=y" >> sdkconfig.defaults
  - idf.py set-target esp32h2
  - idf.py build
  - cd $CI_PROJECT_DIR/examples/esp_zigbee_gateway
  - idf.py set-target esp32s3
  - idf.py build
  - mv $CI_PROJECT_DIR/examples/esp_zigbee_gateway/sdkconfig.defaults.ori $CI_PROJECT_DIR/examples/esp_zigbee_gateway/sdkconfig.defaults
  - cd ${ESP_ZIGBEE_SDK_PATH}

build_non_pytest_examples:
  stage: build
  image: ${CI_DOCKER_REGISTRY}/esp-env-v5.1:1
  artifacts:
    paths:
      - "**/build*/*.bin"
      - "**/build*/flasher_args.json"
      - "**/build*/config/sdkconfig.json"
      - "**/build*/bootloader/*.bin"
      - "**/build*/partition_table/*.bin"
    when: always
    expire_in: 4 days
  script:
    - *update_zigbee_lib_script
    - python tools/ci/build_apps.py ./examples --no_pytest
      --parallel-count ${CI_NODE_TOTAL:-1}
      --parallel-index ${CI_NODE_INDEX:-1}
  parallel: 2
  tags:
    - build

build_non_pytest_host:
    stage: build
    image: ${CI_DOCKER_REGISTRY}/esp-env-v5.1:1
    artifacts:
      when: always
      expire_in: 4 days
    script:
      - *setup_idf
      - cd ${ESP_ZIGBEE_SDK_PATH}
      - python tools/ci/build_apps.py ./examples --host
    tags:
      - build

build_pytest_examples:
  stage: build
  image: ${CI_DOCKER_REGISTRY}/esp-env-v5.1:1
  artifacts:
    paths:
      - "**/build*/*.bin"
      - "**/build*/*.map"
      - "**/build*/*.elf"
      - "**/build*/flasher_args.json"
      - "**/build*/flash_project_args"
      - "**/build*/config/sdkconfig.json"
      - "**/build*/bootloader/*.bin"
      - "**/build*/partition_table/*.bin"
    when: always
    expire_in: 4 days
  script:
    - *update_zigbee_lib_script
    - python tools/ci/build_apps.py ./examples --pytest
  tags:
    - build

build_pytest_gateway:
    stage: build
    image: ${CI_DOCKER_REGISTRY}/esp-env-v5.1:1
    artifacts:
      paths:
        - "**/build*/*.bin"
        - "**/build*/*.map"
        - "**/build*/*.elf"
        - "**/build*/flasher_args.json"
        - "**/build*/flash_project_args"
        - "**/build*/config/sdkconfig.json"
        - "**/build*/bootloader/*.bin"
        - "**/build*/partition_table/*.bin"
      when: always
      expire_in: 4 days
    script:
      - *update_zigbee_lib_script
      - python tools/ci/build_apps.py ./examples --rcp_gateway
      - *build_rcp_gateway
    tags:
      - build

build_docs:
    stage: build
    image: $CI_DOCKER_REGISTRY/esp-idf-doc-env-v5.1:1-1
    variables:
        ESP_DOCS_LATEST_BRANCH_NAME: "main"
    artifacts:
        when: always
        paths:
            - docs/_build/*/*/*.txt
            - docs/_build/*/*/html/*
        expire_in: 1 days
    script:
        - cd docs
        - build-docs -t esp32 esp32c3 esp32h2 esp32s3 esp32c6 -l en

pytest_esp32h2_i154_zigbee_multi_dut:
  stage: target_test
  image: ${CI_DOCKER_REGISTRY}/target-test-env-v5.1:1
  needs:
    - build_pytest_examples
  script:
    - pip install -r tools/ci/requirements-pytest.txt
    - find examples/ -name "pytest_*.py" | xargs pytest --target esp32h2 -m zigbee_multi_dut
  tags: ["esp32h2", "zigbee_multi_dut"]

pytest_esp32c6_i154_zigbee_multi_dut:
  stage: target_test
  image: ${CI_DOCKER_REGISTRY}/target-test-env-v5.1:1
  needs:
    - build_pytest_examples
  script:
    - pip install -r tools/ci/requirements-pytest.txt
    - find examples/ -name "pytest_*.py" | xargs pytest --target esp32c6 -m zigbee_multi_dut
  tags: ["esp32c6", "zigbee_multi_dut"]

pytest_esp32s3_i154_zigbee_multi_dut:
  stage: target_test
  image: ${CI_DOCKER_REGISTRY}/target-test-env-v5.1:1
  needs:
    - build_pytest_gateway
  script:
    - pip install -r tools/ci/requirements-pytest.txt
    - find examples/ -name "pytest_*.py" | xargs pytest --target esp32s3 -m zigbee_multi_dut
  tags: ["esp32s3", "zigbee_multi_dut"]

.deploy_docs_template:
    stage: docs
    image: $CI_DOCKER_REGISTRY/esp-idf-doc-env-v5.1:1-1
    needs:
        - build_docs
    variables:
        ESP_DOCS_LATEST_BRANCH_NAME: "main"
    script:
        - source ${CI_PROJECT_DIR}/docs/utils.sh
        - add_doc_server_ssh_keys $DOCS_DEPLOY_PRIVATEKEY $DOCS_DEPLOY_SERVER $DOCS_DEPLOY_SERVER_USER
        - export GIT_VER=$(git describe --always)
        - deploy-docs
    tags:
        - deploy_docs

deploy_docs_preview:
    extends:
        - .deploy_docs_template
    variables:
        TYPE: "preview"
        DOCS_BUILD_DIR: "${CI_PROJECT_DIR}/docs/_build/"
        DOCS_DEPLOY_PRIVATEKEY: "$DOCS_PREVIEW_DEPLOY_KEY"
        DOCS_DEPLOY_SERVER: "$DOCS_PREVIEW_SERVER"
        DOCS_DEPLOY_SERVER_USER: "$DOCS_PREVIEW_SERVER_USER"
        DOCS_DEPLOY_PATH: "$DOCS_PREVIEW_PATH"
        DOCS_DEPLOY_URL_BASE: "https://$DOCS_PREVIEW_SERVER_URL/docs/esp-zigbee-sdk"

deploy_docs_production:
    only:
        - main
        - /^release\/v/
        - /^v\d+\.\d+/
    extends:
        - .deploy_docs_template
    variables:
        TYPE: "production"
        DOCS_BUILD_DIR: "${CI_PROJECT_DIR}/docs/_build/"
        DOCS_DEPLOY_PRIVATEKEY: "$DOCS_PROD_DEPLOY_KEY"
        DOCS_DEPLOY_SERVER: "$DOCS_PROD_SERVER"
        DOCS_DEPLOY_SERVER_USER: "$DOCS_PROD_SERVER_USER"
        DOCS_DEPLOY_PATH: "$DOCS_PROD_PATH"
        DOCS_DEPLOY_URL_BASE: "https://docs.espressif.com/projects/esp-zigbee-sdk"
